spring.application.name=rag-ai-course
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=qwen2.5:1.5b
spring.ai.ollama.chat.options.temperature=1
server.port=8080

spring.ai.ollama.embedding.options.model=nomic-embed-text

spring.ai.vectorstore.redis.initialize-schema=true

